### ISSUE TITLE
[FR] layer opacity

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#184]
It would be really useful to be able to set a layer opacity.
This is especially useful when drawing raster overlay layers, like weather or slopes.
Without it the labels becomes almost unreadable for covered regions.

**Comment by mtehver** [comment]
Yes, this has been requested several times before in different forms. We will discuss this internally and if possible, will add this in the forthcoming releases.

**Comment by farfromrefug** [comment]
@mtehver amazing!!!

**Comment by jaakla** [comment]
@Nikituh - create internal test/sample for VectorLayer and RasterTileLayer (Swift, Kotlin), test with all platforms and several device versions/models. Just set 0.5 transparency for different layer types.

**Comment by mtehver** [comment]
@jaakla @Nikituh The code has been merged into master branch.

**Comment by jaakla** [comment]
@Nikituh - implement in Routing sample app side, make route line wider.

**Comment by jaakla** [comment]
This is in latest SDK 4.1.3-rc.1 build now, see https://github.com/CartoDB/mobile-sdk/releases/tag/release%2Fv4.1.3-rc.1 . 

@farfromrefug can you try and give feedback? The method/property is just `setOpacity` for all the Layers.

**Comment by farfromrefug** [comment]
@jaakla Sorry for looking at this so late. For me this does not work in 4.1.3 on Android.
I got a method no found exception for ```setOpacity``` from the c++ side. The jar file contains the method but the method does not seem to be there on the c++ side:
```
06-13 09:40:45.431: E/AndroidRuntime(10496): java.lang.NoSuchMethodError: No virtual method setOpacity(F)V in class Lcom/carto/layers/TileLayer; or its super classes (declaration of 'com.carto.layers.TileLayer' appears in /data/app/akylas.alpi.maps-uhU024z2xBkdJGY7sAps4A==/base.apk)
```
I have checked twice, i have the correct so libs

**Comment by Nikituh** [comment]
Hey!

Unfortunately, I cannot reproduce the issue with our sample apps. I tried with AdvancedMap.Swift sample VectorObjectView:

```
vectorLayer?.setOpacity(0.5)
```

as well VectorElementView of AdvancedMap.Kotlin:

```
objectLayer!!.opacity = 0.5f
```

The result is as follows:

![screen shot 2018-06-13 at 15 41 06](https://user-images.githubusercontent.com/8685359/41351842-4c298c70-6f20-11e8-898c-e4114ddd0d54.png)

**Comment by jaakla** [comment]
Is your dependency configured like this? Sometimes Android Studio / Maven or gradle does not refresh library versions fully, it looks like something like that has happened. Cleaning caches, restarts and other quite random actions have resolved this 
```
dependencies {
    implementation('com.carto:carto-mobile-sdk:4.1.3@aar')
...
```

**Comment by farfromrefug** [comment]
@jaakla I don't use gradle. I am working within Titanium Mobile still using ant...
So i copy the jar + so files myself. I downloaded the release from github [here](https://github.com/CartoDB/mobile-sdk/releases/download/release%2Fv4.1.3/sdk4-android-4.1.3.485.c3f91d125050380428eda2b318394a4607f571d5.zip)
@Nikituh i dont know if it is important but i am using ```setOpacity``` only on ```TileLayer```
I know the jar file has the setOpacity as i can see it myself in the jar. I am almost sure the so lib does not have the method. Maybe the github release is a bad one?
I will try and download the aar and use it

**Comment by jaakla** [comment]
.so file in the zip file and .so file seems to be identical, as it should. I don't know Titanium details, but this could have some caching internally also. Note that some older SDK versions had more architectures, we have stripped now to 3 key ones. In quite unlikely case your device maybe does not support any of these?
