### ISSUE TITLE
[ios] NativeScript compatibility

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#175]
I am trying to create a CartoMobile plugin for NativeScript.
I am facing an issue related to the CartoMobile framework.  It wont work because it is missing a required ```module.modulemap```. You can see the explanation [here](https://github.com/NativeScript/ios-runtime/issues/413#issuecomment-159003887)

Also i created a Info.plist inside the framework. But that i am not sure is a requirement.
Creating those 2 files make the framework work correctly
Is there any chance you could update the build process to make the framework compatible (cocoapod too)?

Thanks

**Comment by Nikituh** [comment]
I'm not really familiar with NativeScript, I don't quite understand the issue enough to provide an answer right now. I'll look into it.

> i created a Info.plist inside the framework

That shouldn't be necessary

> Creating those 2 files make the framework work correctly 

What two files?

**Comment by farfromrefug** [comment]
@Nikituh i did create the info.plist too. Thus the 2 files.
I have creating a working basic module for ios.
I am trying to publish it to github, but as i can't use cocoapods for now i have to manually add the framework. And github won't let me publish it as it is too big.

Might zip one for you to try

**Comment by Nikituh** [comment]
I've now had a bit of a look at NativeScript, and damn, the documentation sure is horribly outdated. But, sure, yes, I'd love to take a look at what you've done :)

**Comment by farfromrefug** [comment]
@Nikituh Yes the doc is old. But honestly this is so powerful, and amazingly easy to develop with.
It will requires weeks of work to port all my libraries to it, but i think i have to.

So [here](https://mega.nz/fm/7VVRAYYb) is the sample project. It s really simple to run.
- uncompress
- in the src folder run ```npminstall```
- in the src folder run ```npm run demo.ios --emulator```
BTW it s using my carto API key, i ll let you change it ;)

**Comment by Nikituh** [comment]
I can't get anything out of that link. :( I'm pretty sure the file is tied to your account.

**Comment by farfromrefug** [comment]
@Nikituh sorry about that, thought it would work! [here](https://ufile.io/zajsf) is another one.

**Comment by Nikituh** [comment]
The build fails:

```
ld: framework not found CartoMobileSDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **
```

When I look inside the .xcodeproj itself, the path of CartoMobileSDK does, indeed, point to a location that doesn't exist

**Comment by farfromrefug** [comment]
@Nikituh might be a symlink issue. Can you:
- save the module.modulemap from the framework i sent you
- replace the CartoMobileSDK framework with one you downloaded from the github
- retry

**Comment by Nikituh** [comment]
It's not just a linking issue. The library is on the wrong path. It works if I manually link `node_modules` to in the folder `nativescript-carto 2/demo/platforms` **and** add that path to `Build Settings` > `Framework Search Paths`.

Also building plugins that make use of additional third-party libraries seems to be absolutely supported in NativeScript (https://docs.nativescript.org/plugins/cocoapods) and our SDK's available there (https://cocoapods.org/pods/CartoMobileSDK)

**Comment by Nikituh** [comment]
I created a basic CartoMobileSDK NativeScript plugin: https://github.com/CartoDB/mobile-sdk-nativescript. Just the SDK download from Cocoapods, the API is not exposed.

If you add the dependency and build your application, `module.modulemap` is added to the path
`MyCocoaPodsApp/platforms/ios/internal/metadata-generator/lib/clang/4.0.0/include`

**Comment by farfromrefug** [comment]
@Nikituh Does it work if you try to access NTMapView? For me cocoapods was working but i did have access to the api. I was getting a ```variable not found:NTMapView```

**Comment by Nikituh** [comment]
I haven't found the time to test the plugin yet, but (thanks to your code) wrapped the API and it seems to find the NTMapView object

**Comment by farfromrefug** [comment]
@Nikituh Don't worry i am not really asking you to test it. I juste want to know if you manage to have it working with 4.1.2-rc1 on cocoapods. For me it doesn't. Once it does i will start working on a plugin that i'll put on github. It should be really fast as i already have it working in native java.

**Comment by farfromrefug** [comment]
@Nikituh did you have time to look at automatically adding the module.modulemap in the release?
I still need to add it with rc2 which makes it impossible to use the Pod.
Thanks

**Comment by farfromrefug** [comment]
@Nikituh Don't worry i got time :D Do you want me to share it with or without the modified framework?

**Comment by Nikituh** [comment]
I'll take the whole lot, so it'd work out of the box!

**Comment by farfromrefug** [comment]
here you go https://ufile.io/ghjlu

**Comment by Nikituh** [comment]
Great, got it, thanks 👍

**Comment by Nikituh** [comment]
@farfromrefug is your project supposed to work out-of-the-box? After changing the bundle identifier and development team, I'm getting the following error:

```
ld: framework not found CartoMobileSDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Nikituh** [comment]
How odd, I still can't get your project to build and am, in fact, getting the same errors you pointed out:

```
const mapView:CartoMap = page.getViewById("mapView");
app/main-page.ts(10,11): error TS2322: Type 'ViewBase' is not assignable to type 'CartoMap'.
  Property 'mapView' is missing in type 'ViewBase'.
```
and
```
ld: framework not found CartoMobileSDK
```

Looking at the pathing in XCode, the .framework file is, indeed, missing from where it is pointed:

![screen shot 2018-02-07 at 14 25 16](https://user-images.githubusercontent.com/8685359/35916360-d4b9609a-0c12-11e8-8a50-3abf5adc4058.png)

This may take more time than initially anticipated. I'll need to take a look at plugin creation in depth and what's up with `module.modulemap` and `Info.plist`

In the mean time, development builds are always available at the following link:
https://github.com/CartoDB/mobile-sdk/wiki/Using-dev-build#ios

**Comment by farfromrefug** [comment]
@Nikituh weird that it does not work with the one i sent you. It should.
Thanks for the dev links. Will keep an eye on it

**Comment by Nikituh** [comment]
@farfromrefug 

In the end, I wasn't able to get your project to run. However, the good news is that we decided that the iOS SDK should, indeed, be built as a dynamic library, and that will include the `module.modulemap`.

Hopefully we'll have it by the release of 4.1.2, but I can't make that promise right now.

**Comment by farfromrefug** [comment]
@Nikituh published my first version of my plugin.
https://github.com/farfromrefug/nativescript-carto
I have trick to use your pod because of the missing module files.
After the mod is installed i copy thos files:
https://github.com/farfromrefug/nativescript-carto/tree/master/src-native/ios/FrameworkFix
into the product framework.

I hope you are going to fix this soon!
